server:
  port: ${SHOPPING_CART_SERVICE_PORT:8083}
spring:
  datasource:
    url: ${SHOPPING_CART_DB_URL:jdbc:mysql://localhost:3306/shopping_cart_database}
    username: ${SHOPPING_CART_DB_USERNAME:root}
    password: ${SHOPPING_CART_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
