server:
  port: ${ORDERS_SERVICE_PORT:8082}
spring:
  datasource:
    url: ${ORDERS_DB_URL:jdbc:mysql://localhost:3306/orders_database}
    username: ${ORDERS_DB_USERNAME:root}
    password: ${ORDERS_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate